# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Skipsdesign I
author: Lars Erik Nygård et al
logo: images/skipsing_bilde.png


parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
only_build_toc_files: true
execute:
  execute_notebooks: force
  timeout: 2400


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/skipsing/skipsdesign1  # Online location of your book
  path_to_book: _build/html  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
